### ISSUE TITLE
上传大文件，抛出异常

### ISSUE THREAD

**Issue by chungluensing** [shangguanyongshi/WebFileServer#2]

**Comment by chungluensing** [comment]
错误为：
terminate called after throwing an instance of 'std::invalid_argument'
terminate called recursively
Aborted (core dumped)

**Comment by chungluensing** [comment]
> 感谢！有没有更详细的错误原因呢？

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
当前出错环境在上传约700KB的jpg图像，有时会卡在最终查找边界符位置，有时会直接抛出上述错误

**Comment by shangguanyongshi** [comment]
> > 感谢！有没有更详细的错误原因呢？
> 
> terminate called after throwing an instance of 'std::bad_alloc' what(): std::bad_alloc Aborted (core dumped) 当前出错环境在上传约700KB的jpg图像，有时会卡在最终查找边界符位置，有时会直接抛出上述错误

原来我测试过7~8M大小的文件是没有问题的，你现在发现的可能是其他的bug，我再去测试一下代码，看看会不会找到你这个报错。你也可以试试复现一下这个bug，可以的话可以调试找一下问题，提交PR。或者试试能不能找到出错的原因和位置，给出一些详细的错误复现过程，谢谢！

**Comment by chungluensing** [comment]
抱歉，我这边还是没找到错误，下方为post上传请求的输出：
20:42:34.23476 2023-03-24 [info]: 新可读事件添加成功，线程池事件队列中剩余的事件个数：1
20:42:34.23547 2023-03-24 [info]: 新可读事件添加成功，线程池事件队列中剩余的事件个数：2
20:42:34.23596 2023-03-24 [info]: 线程 20:42:34.23601 2023-03-24 [info]: 4线程  收到事件1 收到事件
20:42:34.23627 2023-03-24 [info]: 线程 1 开始处理事件
20:42:34.23656 2023-03-24 [info]: 开始处理客户端 5 的一个 HandleRecv 事件
20:42:34.23673 2023-03-24 [info]: 线程 4 开始处理事件
20:42:34.23688 2023-03-24 [info]: 开始处理客户端 5 的一个 HandleRecv 事件
20:42:34.23813 2023-03-24 [info]: 新可读事件添加成功，线程池事件队列中剩余的事件个数：1
20:42:34.23870 2023-03-24 [info]: 新可读事件添加成功，线程池事件队列中剩余的事件个数：2
20:42:34.23891 2023-03-24 [info]: 线程 3 收到事件
20:42:34.23907 2023-03-24 [info]: 线程 2 收到事件
20:42:34.23925 2023-03-24 [info]: 线程 2 开始处理事件
20:42:34.23917 2023-03-24 [info]: 线程 3 开始处理事件
20:42:34.23945 2023-03-24 [info]: 处理客户端 5 的请求行完成
20:42:34.23948 2023-03-24 [info]: 开始处理客户端 5 的一个 HandleRecv 事件
20:42:34.23933 2023-03-24 [info]: 开始处理客户端 5 的一个 HandleRecv 事件
20:42:34.24173 2023-03-24 [info]: 处理客户端 5 的消息首部完成
20:42:34.24193 2023-03-24 [info]: 客户端 5 发送 POST 请求，开始处理请求体
20:42:34.24198 2023-03-24 [info]: 客户端 5 的 POST 请求用于上传文件，寻找文件头开始边界...
20:42:34.24227 2023-03-24 [info]: 客户端 5 的 POST 请求体中找到文件头开始边界，正在处理文件头...
20:42:34.24246 2023-03-24 [info]: 客户端 5 的 POST 请求体中找到文件名字 Hippopx.jpg ，继续处理文件头...
20:42:34.24288 2023-03-24 [info]: 新可读事件添加成功，线程池事件队列中剩余的事件个数：1
20:42:34.24292 2023-03-24 [info]: 客户端 5 的 POST 请求体中文件头处理成功，正在接收
![QQ图片20230324204308](https://user-images.githubusercontent.com/62226509/227524588-98af77f7-bffd-4806-8a43-c11d35cbec0e.png)
并保存文件内容...

**Comment by shangguanyongshi** [comment]
> 抱歉，我这边还是没找到错误，下方为post上传请求的输出（会卡在上传过程中）： 20:42:34.23476 2023-03-24 [info]: 新可读事件添加成功，线程池事件队列中剩余的事件个数：1 20:42:34.23547 2023-03-24 [info]: 新可读事件添加成功，线程池事件队列中剩余的事件个数：2 20:42:34.23596 2023-03-24 [info]: 线程 20:42:34.23601 2023-03-24 [info]: 4线程 收到事件1 收到事件 20:42:34.23627 2023-03-24 [info]: 线程 1 开始处理事件 20:42:34.23656 2023-03-24 [info]: 开始处理客户端 5 的一个 HandleRecv 事件 20:42:34.23673 2023-03-24 [info]: 线程 4 开始处理事件 20:42:34.23688 2023-03-24 [info]: 开始处理客户端 5 的一个 HandleRecv 事件 20:42:34.23813 2023-03-24 [info]: 新可读事件添加成功，线程池事件队列中剩余的事件个数：1 20:42:34.23870 2023-03-24 [info]: 新可读事件添加成功，线程池事件队列中剩余的事件个数：2 20:42:34.23891 2023-03-24 [info]: 线程 3 收到事件 20:42:34.23907 2023-03-24 [info]: 线程 2 收到事件 20:42:34.23925 2023-03-24 [info]: 线程 2 开始处理事件 20:42:34.23917 2023-03-24 [info]: 线程 3 开始处理事件 20:42:34.23945 2023-03-24 [info]: 处理客户端 5 的请求行完成 20:42:34.23948 2023-03-24 [info]: 开始处理客户端 5 的一个 HandleRecv 事件 20:42:34.23933 2023-03-24 [info]: 开始处理客户端 5 的一个 HandleRecv 事件 20:42:34.24173 2023-03-24 [info]: 处理客户端 5 的消息首部完成 20:42:34.24193 2023-03-24 [info]: 客户端 5 发送 POST 请求，开始处理请求体 20:42:34.24198 2023-03-24 [info]: 客户端 5 的 POST 请求用于上传文件，寻找文件头开始边界... 20:42:34.24227 2023-03-24 [info]: 客户端 5 的 POST 请求体中找到文件头开始边界，正在处理文件头... 20:42:34.24246 2023-03-24 [info]: 客户端 5 的 POST 请求体中找到文件名字 Hippopx.jpg ，继续处理文件头... 20:42:34.24288 2023-03-24 [info]: 新可读事件添加成功，线程池事件队列中剩余的事件个数：1 20:42:34.24292 2023-03-24 [info]: 客户端 5 的 POST 请求体中文件头处理成功，正在接收 ![QQ图片20230324204308](https://user-images.githubusercontent.com/62226509/227524588-98af77f7-bffd-4806-8a43-c11d35cbec0e.png) 并保存文件内容...

好的，我参考一下去看看，找到了告诉你

**Comment by chungluensing** [comment]
博主你好，上传文件抛出异常的bug，感觉是HandleRecv::process()函数中对于接受没完成的数据未再次重新注册epolloneshot。

**Comment by chungluensing** [comment]
bug找到了，函数HandleSend::process() 中状态为HADNLE_COMPLATE时应将modifyWaitFd(m_epollFd, m_clientFd, true, true, false)。

**Comment by shangguanyongshi** [comment]
> bug找到了，函数HandleSend::process() 中状态为HADNLE_COMPLATE时应将modifyWaitFd(m_epollFd, m_clientFd, true, true, false)。

哈哈，我还在排查呢，你可以提交个 PR。非常感谢

**Comment by shangguanyongshi** [comment]
同学你看你可以抽时间修复一下这个bug，提交一下PR哈
