### ISSUE TITLE
设置fd非阻塞

### ISSUE THREAD

**Issue by 1900100209** [shangguanyongshi/WebFileServer#7]
```cpp
// 设置文件描述符为非阻塞

int setNonBlocking(int fd){
    int oldFlag = fcntl(fd, F_GETFL);
    int ret = fcntl(fd, F_GETFL, oldFlag | O_NONBLOCK);//这里应该是F_SETFL吧
    if(ret != 0){
        return -1;
    }
    return 0;
}
```

**Comment by shangguanyongshi** [comment]
> ```c++
> // 设置文件描述符为非阻塞
> 
> int setNonBlocking(int fd){
>     int oldFlag = fcntl(fd, F_GETFL);
>     int ret = fcntl(fd, F_GETFL, oldFlag | O_NONBLOCK);//这里应该是F_SETFL吧
>     if(ret != 0){
>         return -1;
>     }
>     return 0;
> }
> ```

对的对的，当时应该是写错了，我马上去修改一下
